name: open_mail
description: A Flutter package to query the device for installed email apps and open them programmatically.
version: 0.0.7
homepage: https://github.com/Cuboid-Inc/open_mail
repository: https://github.com/Cuboid-Inc/open_mail

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:

topics:
  - mail
  - open-mail
  - app
  - mail-app

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.cuboid.open_mail
        pluginClass: OpenMailAppPlugin
      ios:
        pluginClass: OpenMailAppPlugin
